### ISSUE TITLE
Option does not exists --plain

### ISSUE THREAD

**Issue by zanematthew** [laravel/quickstart-intermediate#13]
When the following command is ran `php artisan make:controller TaskController --plain`, the following error is displayed:

```
  [Symfony\Component\Console\Exception\RuntimeException]
  The "--plain" option does not exist.
```

**Comment by wedojava** [comment]
hi,
it's means that, your version is 5.2,in 5.2 only one option to use is `--resource`, 5.1 's `--plain` is instead of no option or parameters.

so,you can do this:
`php artisan make:controller TaskController`
if you want the older versions controller,you can do this:
`php artisan make:controller TaskController --resource`

**Comment by petermichaux** [comment]
`--plain` has been removed from the tutorial.

Can this issue be closed?

**Comment by Tangyanxin** [comment]
@wedojava @petermichaux thank you .

**Comment by Molinex** [comment]
@wedojava 
Thank you man.

**Comment by VivekkChudasama** [comment]
@wedojava Thank you .

**Comment by ithinkiborkedit** [comment]
https://laravel.com/docs/5.4/artisan

Reference to "--plain" still exists here.

**Comment by new-comet-dev** [comment]
Thanks

**Comment by dongthuhoang** [comment]
When the following command is ran >php artisan make:migration create_product_table --create-product
the following error is displayed: [Symfony\Component\Console \Exception\RuntimeException]
The "--create-product" option dose not exist.

Help me, please.

**Comment by bonheur-agblevon** [comment]
it is **--create=product** not **--create-product**

**Comment by blackinitial** [comment]
thanks

**Comment by almusalmi** [comment]
thanks, i use laravel 5.6

**Comment by almusalmi** [comment]
how is work in version 5.6

**Comment by almusalmi** [comment]
how is work in version 5.6

**Comment by almusalmi** [comment]
please help me
