### ISSUE TITLE
vendor directory is missing

### ISSUE THREAD

**Issue by Win0ver** [laravel/quickstart-intermediate#14]
...which lead to a 500 server error with php logs:

PHP Fatal error:  require(): Failed opening required '/Applications/MAMP/htdocs/laravel/bootstrap/../vendor/autoload.php'

Copying the vendor directory from a fresh install gives the following error:

FatalErrorException in ProviderRepository.php line 146:
Class 'Illuminate\Routing\ControllerServiceProvider' not found

**Comment by GrahamCampbell** [comment]
You didn't run composer install.

**Comment by GrahamCampbell** [comment]
You can't just "copy" a vendor folder over.

**Comment by Win0ver** [comment]
Thank you.
