### ISSUE TITLE
TokenMismatchException in VerifyCsrfToken.php line 67

### ISSUE THREAD

**Issue by evertramos** [laravel/quickstart-intermediate#15]
Hi there!

I clone the repository, install dependecies and migrate the database. Although, when trying to register I get the error:

<code>TokenMismatchException in VerifyCsrfToken.php line 67</code>

I try the 5.2 branch and comes up with the same error...

**Comment by pravash-upreti** [comment]
I have also same.

**Comment by joenmarz** [comment]
Same here. But I've found the answer here http://stackoverflow.com/questions/34866404/tokenmismatchexception-in-verifycsrftoken-php-line-67

**Comment by evertramos** [comment]
Please check the crsf token in the views:

<input type="hidden" name="_token" value="{{ csrf_token() }}">

And also, make sure you have the .env file settle up, with a key:

php artisan key:generate

**Comment by bastolakancha123** [comment]
Same Condition with me too..

**Comment by kevosomi** [comment]
Well, the solution for this error is pretty simple. Normally, when you want to quickly test out a fresh install of Laravel most of us result to using the in built server initiated through "php artisan serve" in the command line. From my research, and I stand to be corrected, this is the cause of the error. To get your application running in Windows, setup a virtual host, using Xampp or Wampp, and your app will be up and running in no time.

**Comment by mukama** [comment]
By default session cookies will only be sent back to the server if the browser has a **HTTPS** connection. You can turn it off in your .env file

    SESSION_SECURE_COOKIE=false

Or you can turn it off in config/session.php

    'secure' => false,

**Comment by patelsagar** [comment]
My Local not error CsrfToken but live server error "TokenMismatchException in VerifyCsrfToken.php line 67:"
Please Any help Me

**Comment by kevosomi** [comment]
@patelsagar just generate a new secret key and you will be fine. 

php artisan key:generate

**Comment by giftymalik** [comment]
I was facing such exception because of POST Content-Length Limit. I guess Laravel's exceptions are not throwing relevant messages.
https://twitter.com/GiftyMalik/status/801433322706518016

**Comment by Qh0stM4N** [comment]
@patelsagar ı have a same problem. If you can solve the problem, I am curious about the solution.

**Comment by sagarshah16** [comment]
@patelsagar  @Qh0stM4N : Have you guys find a solution ? I am having the same problem.

**Comment by cpapidas** [comment]
i have the same problem too

**Comment by pravash-upreti** [comment]
Please check if you have any file or route file begin with [enter] and <?php .
Remember there should not be any white space and line break in php file . 
when u host project to linux server you will get token TokenMismatchException error .

**Comment by cpapidas** [comment]
all the files is ok. Laravel 5 has so many bugs

**Comment by zeelz** [comment]
I have same issue when I was trying out Laravel 5.2 at first, then I learnt about `{{!! csrf_field() !!}} `to be added in the form and that solved it. But later I learnt about Form Helpers, this takes care of CSRF protection and does not give any errors. Though Form Helpers are not legitimately available after Laravel 5.2, you can still use them from [LaravelCollective](http://LaravelCollective.com).

**Comment by Qh0stM4N** [comment]
@cpapidas @sagarshah16 not solved 👎local is fine but server down session.
After a long search I could not find a solution. I could not even identify the source of the problem.
I can recommend to install the latest version of the laravel and move the old application code.
fix problem maybe in a short time.
