### ISSUE TITLE
--plain in artisan command 'php artisan make:controller <Controller Name> --plain' doen't work.

### ISSUE THREAD

**Issue by rolandtacadena** [laravel/quickstart-intermediate#16]
When I tried to follow the intermediate lesson in laravel documentation https://laravel.com/docs/5.2/quickstart-intermediate
 
The command generate exception:

[Symfony\Component\Console\Exception\RuntimeException]
  The "--plain" option does not exist.

When I remove the '--plain' in simply generates a plain controller?

The documentation must be updated to inform that we don't need to insert the '--plain' option in creating controllers.

**Comment by GrahamCampbell** [comment]
Please send a PR to the docs and close this issue.

**Comment by petermichaux** [comment]
`--plain` has been removed from the docs.

Can this issue be closed?
