### ISSUE TITLE
Any plans for "Advanced Task List" tutorial?

### ISSUE THREAD

**Issue by tenzan** [laravel/quickstart-intermediate#20]
Any plans for "Advanced Task List" tutorial, where you show in details the stuff you've skipped in the `Intermediate` version?

**Comment by petermichaux** [comment]
Which stuff was skipped in the intermediate tutorial?

**Comment by tenzan** [comment]
Bootstrap and Authentication details as described https://github.com/laravel/quickstart-intermediate/issues/19

**Comment by petermichaux** [comment]
That stuff is all part of this example and I think the intermediate tutorial should discuss it. It shouldn't be punted to an advanced tutorial.

There is one omission in the tutorial about the `RedirectifAuthenticated.php` change. That just needs to be added to the tutorial.

It is questionable if all the Bootstrap stuff should be explained in the tutorial or not. I can see arguments both ways. It is long and distracts from what is specific to Laravel.

**Comment by tenzan** [comment]
I assumed there is laravel way of adding bootstrap stuff...

**Comment by petermichaux** [comment]
`php artisan make:auth --views` adds bootstrap in the app's layout

**Comment by tenzan** [comment]
Thanks.

**Comment by petermichaux** [comment]
The tutorial now contains information about `RedirectifAuthenticated.php`.

Can this issue be closed?

**Comment by tenzan** [comment]
Thanks a lot. I will close with this comment.
