### ISSUE TITLE
Undefined variable: errors

### ISSUE THREAD

**Issue by xzjs** [laravel/quickstart-intermediate#27]
I according to the tutorial step by step, but there have a problem,"Undefined variable: errors (View: /Applications/MAMP/htdocs/WorkReport/resources/views/auth/login.blade.php)",what should id do?
[http://www.golaravel.com/laravel/docs/5.1/quickstart-intermediate/](http://www.golaravel.com/laravel/docs/5.1/quickstart-intermediate/)

**Comment by mattmoore83** [comment]
I just encountered the same issue, it would appear that you need to wrap routes with the following:

Route::group(['middleware' => ['web']], function () {
    //routes here
}

Just like in https://github.com/laravel/quickstart-intermediate/blob/master/app/Http/routes.php

Hope that helps!

**Comment by GrahamCampbell** [comment]
That's only needed for the 5.2 version, not the 5.1 version.

**Comment by xzjs** [comment]
thanks for everyone，it is my bug,i delete the user,sorry to everyone
